# Generated by Django 2.0.6 on 2018-06-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiraFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('bandeira', models.ImageField(upload_to='./uploads')),
            ],
        ),
        migrations.AddField(
            model_name='primeirafase',
            name='mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='api.Time'),
        ),
        migrations.AddField(
            model_name='primeirafase',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='api.Time'),
        ),
    ]
