# Generated by Django 2.0.6 on 2018-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeirafase',
            name='gol_mandante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gol Mandante'),
        ),
        migrations.AddField(
            model_name='primeirafase',
            name='gol_visitante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gol Visitante'),
        ),
    ]
