# Generated by Django 2.0.6 on 2018-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180607_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeirafase',
            name='grupo',
            field=models.CharField(default='', max_length=1),
        ),
    ]
